/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './src/routes/__root'
import { Route as ReservarIndexImport } from './src/routes/reservar/index'
import { Route as PublicarviajeIndexImport } from './src/routes/publicarviaje/index'
import { Route as HomeIndexImport } from './src/routes/home/index'
import { Route as AyudaIndexImport } from './src/routes/ayuda/index'
import { Route as AccountIndexImport } from './src/routes/account/index'
import { Route as WalletIndexImport } from './src/routes/Wallet/index'
import { Route as ReservasIndexImport } from './src/routes/Reservas/index'
import { Route as RegistroIndexImport } from './src/routes/Registro/index'
import { Route as RegistrarVehiculoIndexImport } from './src/routes/RegistrarVehiculo/index'
import { Route as RecuperarPaswordIndexImport } from './src/routes/RecuperarPasword/index'
import { Route as PerfilIndexImport } from './src/routes/Perfil/index'
import { Route as ParadasIndexImport } from './src/routes/Paradas/index'
import { Route as OrigenIndexImport } from './src/routes/Origen/index'
import { Route as LoginIndexImport } from './src/routes/Login/index'
import { Route as DetallesViajeIndexImport } from './src/routes/DetallesViaje/index'
import { Route as DestinoIndexImport } from './src/routes/Destino/index'
import { Route as DateSelectedIndexImport } from './src/routes/DateSelected/index'
import { Route as CuposReservadosIndexImport } from './src/routes/CuposReservados/index'
import { Route as CuposIndexImport } from './src/routes/Cupos/index'
import { Route as CuponesIndexImport } from './src/routes/Cupones/index'
import { Route as CompletarRegistroIndexImport } from './src/routes/CompletarRegistro/index'
import { Route as ChatIndexImport } from './src/routes/Chat/index'
import { Route as ActividadesIndexImport } from './src/routes/Actividades/index'
import { Route as ReservasTripReservationModalImport } from './src/routes/Reservas/TripReservationModal'
import { Route as RegistrarVehiculoSoatImport } from './src/routes/RegistrarVehiculo/Soat'
import { Route as RegistrarVehiculoPropertyCardImport } from './src/routes/RegistrarVehiculo/PropertyCard'
import { Route as RegistrarVehiculoLicenseImport } from './src/routes/RegistrarVehiculo/License'
import { Route as RegistrarVehiculoDocumentsRequiredImport } from './src/routes/RegistrarVehiculo/DocumentsRequired'
import { Route as RegistrarVehiculoDocumentFormImport } from './src/routes/RegistrarVehiculo/DocumentForm'
import { Route as RecuperarPaswordForgotPasswordImport } from './src/routes/RecuperarPasword/ForgotPassword'
import { Route as CuposViewTicketImport } from './src/routes/Cupos/ViewTicket'
import { Route as CuposViewPassengersImport } from './src/routes/Cupos/ViewPassengers'
import { Route as CuposViewBookingDetailsImport } from './src/routes/Cupos/ViewBookingDetails'
import { Route as ActividadesActividadesPageImport } from './src/routes/Actividades/ActividadesPage'
import { Route as CuposReservadosValidarCupoBookingIdImport } from './src/routes/CuposReservados/ValidarCupo.$bookingId'
// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./src/routes/index.lazy').then((d) => d.Route))

const ReservarIndexRoute = ReservarIndexImport.update({
  id: '/reservar/',
  path: '/reservar/',
  getParentRoute: () => rootRoute,
} as any)

const PublicarviajeIndexRoute = PublicarviajeIndexImport.update({
  id: '/publicarviaje/',
  path: '/publicarviaje/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const AyudaIndexRoute = AyudaIndexImport.update({
  id: '/ayuda/',
  path: '/ayuda/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIndexRoute = AccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const WalletIndexRoute = WalletIndexImport.update({
  id: '/Wallet/',
  path: '/Wallet/',
  getParentRoute: () => rootRoute,
} as any)

const ReservasIndexRoute = ReservasIndexImport.update({
  id: '/Reservas/',
  path: '/Reservas/',
  getParentRoute: () => rootRoute,
} as any)

const RegistroIndexRoute = RegistroIndexImport.update({
  id: '/Registro/',
  path: '/Registro/',
  getParentRoute: () => rootRoute,
} as any)

const RegistrarVehiculoIndexRoute = RegistrarVehiculoIndexImport.update({
  id: '/RegistrarVehiculo/',
  path: '/RegistrarVehiculo/',
  getParentRoute: () => rootRoute,
} as any)

const RecuperarPaswordIndexRoute = RecuperarPaswordIndexImport.update({
  id: '/RecuperarPasword/',
  path: '/RecuperarPasword/',
  getParentRoute: () => rootRoute,
} as any)

const PerfilIndexRoute = PerfilIndexImport.update({
  id: '/Perfil/',
  path: '/Perfil/',
  getParentRoute: () => rootRoute,
} as any)

const ParadasIndexRoute = ParadasIndexImport.update({
  id: '/Paradas/',
  path: '/Paradas/',
  getParentRoute: () => rootRoute,
} as any)

const OrigenIndexRoute = OrigenIndexImport.update({
  id: '/Origen/',
  path: '/Origen/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/Login/',
  path: '/Login/',
  getParentRoute: () => rootRoute,
} as any)

const DetallesViajeIndexRoute = DetallesViajeIndexImport.update({
  id: '/DetallesViaje/',
  path: '/DetallesViaje/',
  getParentRoute: () => rootRoute,
} as any)

const DestinoIndexRoute = DestinoIndexImport.update({
  id: '/Destino/',
  path: '/Destino/',
  getParentRoute: () => rootRoute,
} as any)

const DateSelectedIndexRoute = DateSelectedIndexImport.update({
  id: '/DateSelected/',
  path: '/DateSelected/',
  getParentRoute: () => rootRoute,
} as any)

const CuposReservadosIndexRoute = CuposReservadosIndexImport.update({
  id: '/CuposReservados/',
  path: '/CuposReservados/',
  getParentRoute: () => rootRoute,
} as any)

const CuposIndexRoute = CuposIndexImport.update({
  id: '/Cupos/',
  path: '/Cupos/',
  getParentRoute: () => rootRoute,
} as any)

const CuponesIndexRoute = CuponesIndexImport.update({
  id: '/Cupones/',
  path: '/Cupones/',
  getParentRoute: () => rootRoute,
} as any)

const CompletarRegistroIndexRoute = CompletarRegistroIndexImport.update({
  id: '/CompletarRegistro/',
  path: '/CompletarRegistro/',
  getParentRoute: () => rootRoute,
} as any)

const ChatIndexRoute = ChatIndexImport.update({
  id: '/Chat/',
  path: '/Chat/',
  getParentRoute: () => rootRoute,
} as any)

const ActividadesIndexRoute = ActividadesIndexImport.update({
  id: '/Actividades/',
  path: '/Actividades/',
  getParentRoute: () => rootRoute,
} as any)

const ReservasTripReservationModalRoute =
  ReservasTripReservationModalImport.update({
    id: '/Reservas/TripReservationModal',
    path: '/Reservas/TripReservationModal',
    getParentRoute: () => rootRoute,
  } as any)

const RegistrarVehiculoSoatRoute = RegistrarVehiculoSoatImport.update({
  id: '/RegistrarVehiculo/Soat',
  path: '/RegistrarVehiculo/Soat',
  getParentRoute: () => rootRoute,
} as any)

const RegistrarVehiculoPropertyCardRoute =
  RegistrarVehiculoPropertyCardImport.update({
    id: '/RegistrarVehiculo/PropertyCard',
    path: '/RegistrarVehiculo/PropertyCard',
    getParentRoute: () => rootRoute,
  } as any)

const RegistrarVehiculoLicenseRoute = RegistrarVehiculoLicenseImport.update({
  id: '/RegistrarVehiculo/License',
  path: '/RegistrarVehiculo/License',
  getParentRoute: () => rootRoute,
} as any)

const RegistrarVehiculoDocumentsRequiredRoute =
  RegistrarVehiculoDocumentsRequiredImport.update({
    id: '/RegistrarVehiculo/DocumentsRequired',
    path: '/RegistrarVehiculo/DocumentsRequired',
    getParentRoute: () => rootRoute,
  } as any)

const RegistrarVehiculoDocumentFormRoute =
  RegistrarVehiculoDocumentFormImport.update({
    id: '/RegistrarVehiculo/DocumentForm',
    path: '/RegistrarVehiculo/DocumentForm',
    getParentRoute: () => rootRoute,
  } as any)

const RecuperarPaswordForgotPasswordRoute =
  RecuperarPaswordForgotPasswordImport.update({
    id: '/RecuperarPasword/ForgotPassword',
    path: '/RecuperarPasword/ForgotPassword',
    getParentRoute: () => rootRoute,
  } as any)

const CuposViewTicketRoute = CuposViewTicketImport.update({
  id: '/Cupos/ViewTicket',
  path: '/Cupos/ViewTicket',
  getParentRoute: () => rootRoute,
} as any)

const CuposViewPassengersRoute = CuposViewPassengersImport.update({
  id: '/Cupos/ViewPassengers',
  path: '/Cupos/ViewPassengers',
  getParentRoute: () => rootRoute,
} as any)

const CuposViewBookingDetailsRoute = CuposViewBookingDetailsImport.update({
  id: '/Cupos/ViewBookingDetails',
  path: '/Cupos/ViewBookingDetails',
  getParentRoute: () => rootRoute,
} as any)

const ActividadesActividadesPageRoute = ActividadesActividadesPageImport.update(
  {
    id: '/Actividades/ActividadesPage',
    path: '/Actividades/ActividadesPage',
    getParentRoute: () => rootRoute,
  } as any,
)

const CuposReservadosValidarCupoBookingIdRoute =
  CuposReservadosValidarCupoBookingIdImport.update({
    id: '/CuposReservados/ValidarCupo/$bookingId',
    path: '/CuposReservados/ValidarCupo/$bookingId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/Actividades/ActividadesPage': {
      id: '/Actividades/ActividadesPage'
      path: '/Actividades/ActividadesPage'
      fullPath: '/Actividades/ActividadesPage'
      preLoaderRoute: typeof ActividadesActividadesPageImport
      parentRoute: typeof rootRoute
    }
    '/Cupos/ViewBookingDetails': {
      id: '/Cupos/ViewBookingDetails'
      path: '/Cupos/ViewBookingDetails'
      fullPath: '/Cupos/ViewBookingDetails'
      preLoaderRoute: typeof CuposViewBookingDetailsImport
      parentRoute: typeof rootRoute
    }
    '/Cupos/ViewPassengers': {
      id: '/Cupos/ViewPassengers'
      path: '/Cupos/ViewPassengers'
      fullPath: '/Cupos/ViewPassengers'
      preLoaderRoute: typeof CuposViewPassengersImport
      parentRoute: typeof rootRoute
    }
    '/Cupos/ViewTicket': {
      id: '/Cupos/ViewTicket'
      path: '/Cupos/ViewTicket'
      fullPath: '/Cupos/ViewTicket'
      preLoaderRoute: typeof CuposViewTicketImport
      parentRoute: typeof rootRoute
    }
    '/RecuperarPasword/ForgotPassword': {
      id: '/RecuperarPasword/ForgotPassword'
      path: '/RecuperarPasword/ForgotPassword'
      fullPath: '/RecuperarPasword/ForgotPassword'
      preLoaderRoute: typeof RecuperarPaswordForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/RegistrarVehiculo/DocumentForm': {
      id: '/RegistrarVehiculo/DocumentForm'
      path: '/RegistrarVehiculo/DocumentForm'
      fullPath: '/RegistrarVehiculo/DocumentForm'
      preLoaderRoute: typeof RegistrarVehiculoDocumentFormImport
      parentRoute: typeof rootRoute
    }
    '/RegistrarVehiculo/DocumentsRequired': {
      id: '/RegistrarVehiculo/DocumentsRequired'
      path: '/RegistrarVehiculo/DocumentsRequired'
      fullPath: '/RegistrarVehiculo/DocumentsRequired'
      preLoaderRoute: typeof RegistrarVehiculoDocumentsRequiredImport
      parentRoute: typeof rootRoute
    }
    '/RegistrarVehiculo/License': {
      id: '/RegistrarVehiculo/License'
      path: '/RegistrarVehiculo/License'
      fullPath: '/RegistrarVehiculo/License'
      preLoaderRoute: typeof RegistrarVehiculoLicenseImport
      parentRoute: typeof rootRoute
    }
    '/RegistrarVehiculo/PropertyCard': {
      id: '/RegistrarVehiculo/PropertyCard'
      path: '/RegistrarVehiculo/PropertyCard'
      fullPath: '/RegistrarVehiculo/PropertyCard'
      preLoaderRoute: typeof RegistrarVehiculoPropertyCardImport
      parentRoute: typeof rootRoute
    }
    '/RegistrarVehiculo/Soat': {
      id: '/RegistrarVehiculo/Soat'
      path: '/RegistrarVehiculo/Soat'
      fullPath: '/RegistrarVehiculo/Soat'
      preLoaderRoute: typeof RegistrarVehiculoSoatImport
      parentRoute: typeof rootRoute
    }
    '/Reservas/TripReservationModal': {
      id: '/Reservas/TripReservationModal'
      path: '/Reservas/TripReservationModal'
      fullPath: '/Reservas/TripReservationModal'
      preLoaderRoute: typeof ReservasTripReservationModalImport
      parentRoute: typeof rootRoute
    }
    '/Actividades/': {
      id: '/Actividades/'
      path: '/Actividades'
      fullPath: '/Actividades'
      preLoaderRoute: typeof ActividadesIndexImport
      parentRoute: typeof rootRoute
    }
    '/Chat/': {
      id: '/Chat/'
      path: '/Chat'
      fullPath: '/Chat'
      preLoaderRoute: typeof ChatIndexImport
      parentRoute: typeof rootRoute
    }
    '/CompletarRegistro/': {
      id: '/CompletarRegistro/'
      path: '/CompletarRegistro'
      fullPath: '/CompletarRegistro'
      preLoaderRoute: typeof CompletarRegistroIndexImport
      parentRoute: typeof rootRoute
    }
    '/Cupones/': {
      id: '/Cupones/'
      path: '/Cupones'
      fullPath: '/Cupones'
      preLoaderRoute: typeof CuponesIndexImport
      parentRoute: typeof rootRoute
    }
    '/Cupos/': {
      id: '/Cupos/'
      path: '/Cupos'
      fullPath: '/Cupos'
      preLoaderRoute: typeof CuposIndexImport
      parentRoute: typeof rootRoute
    }
    '/CuposReservados/': {
      id: '/CuposReservados/'
      path: '/CuposReservados'
      fullPath: '/CuposReservados'
      preLoaderRoute: typeof CuposReservadosIndexImport
      parentRoute: typeof rootRoute
    }
    '/DateSelected/': {
      id: '/DateSelected/'
      path: '/DateSelected'
      fullPath: '/DateSelected'
      preLoaderRoute: typeof DateSelectedIndexImport
      parentRoute: typeof rootRoute
    }
    '/Destino/': {
      id: '/Destino/'
      path: '/Destino'
      fullPath: '/Destino'
      preLoaderRoute: typeof DestinoIndexImport
      parentRoute: typeof rootRoute
    }
    '/DetallesViaje/': {
      id: '/DetallesViaje/'
      path: '/DetallesViaje'
      fullPath: '/DetallesViaje'
      preLoaderRoute: typeof DetallesViajeIndexImport
      parentRoute: typeof rootRoute
    }
    '/Login/': {
      id: '/Login/'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/Origen/': {
      id: '/Origen/'
      path: '/Origen'
      fullPath: '/Origen'
      preLoaderRoute: typeof OrigenIndexImport
      parentRoute: typeof rootRoute
    }
    '/Paradas/': {
      id: '/Paradas/'
      path: '/Paradas'
      fullPath: '/Paradas'
      preLoaderRoute: typeof ParadasIndexImport
      parentRoute: typeof rootRoute
    }
    '/Perfil/': {
      id: '/Perfil/'
      path: '/Perfil'
      fullPath: '/Perfil'
      preLoaderRoute: typeof PerfilIndexImport
      parentRoute: typeof rootRoute
    }
    '/RecuperarPasword/': {
      id: '/RecuperarPasword/'
      path: '/RecuperarPasword'
      fullPath: '/RecuperarPasword'
      preLoaderRoute: typeof RecuperarPaswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/RegistrarVehiculo/': {
      id: '/RegistrarVehiculo/'
      path: '/RegistrarVehiculo'
      fullPath: '/RegistrarVehiculo'
      preLoaderRoute: typeof RegistrarVehiculoIndexImport
      parentRoute: typeof rootRoute
    }
    '/Registro/': {
      id: '/Registro/'
      path: '/Registro'
      fullPath: '/Registro'
      preLoaderRoute: typeof RegistroIndexImport
      parentRoute: typeof rootRoute
    }
    '/Reservas/': {
      id: '/Reservas/'
      path: '/Reservas'
      fullPath: '/Reservas'
      preLoaderRoute: typeof ReservasIndexImport
      parentRoute: typeof rootRoute
    }
    '/Wallet/': {
      id: '/Wallet/'
      path: '/Wallet'
      fullPath: '/Wallet'
      preLoaderRoute: typeof WalletIndexImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/ayuda/': {
      id: '/ayuda/'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/publicarviaje/': {
      id: '/publicarviaje/'
      path: '/publicarviaje'
      fullPath: '/publicarviaje'
      preLoaderRoute: typeof PublicarviajeIndexImport
      parentRoute: typeof rootRoute
    }
    '/reservar/': {
      id: '/reservar/'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarIndexImport
      parentRoute: typeof rootRoute
    }
    '/CuposReservados/ValidarCupo/$bookingId': {
      id: '/CuposReservados/ValidarCupo/$bookingId'
      path: '/CuposReservados/ValidarCupo/$bookingId'
      fullPath: '/CuposReservados/ValidarCupo/$bookingId'
      preLoaderRoute: typeof CuposReservadosValidarCupoBookingIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/RegistrarVehiculo/DocumentForm': typeof RegistrarVehiculoDocumentFormRoute
  '/RegistrarVehiculo/DocumentsRequired': typeof RegistrarVehiculoDocumentsRequiredRoute
  '/RegistrarVehiculo/License': typeof RegistrarVehiculoLicenseRoute
  '/RegistrarVehiculo/PropertyCard': typeof RegistrarVehiculoPropertyCardRoute
  '/RegistrarVehiculo/Soat': typeof RegistrarVehiculoSoatRoute
  '/Reservas/TripReservationModal': typeof ReservasTripReservationModalRoute
  '/Actividades': typeof ActividadesIndexRoute
  '/Chat': typeof ChatIndexRoute
  '/CompletarRegistro': typeof CompletarRegistroIndexRoute
  '/Cupones': typeof CuponesIndexRoute
  '/Cupos': typeof CuposIndexRoute
  '/CuposReservados': typeof CuposReservadosIndexRoute
  '/DateSelected': typeof DateSelectedIndexRoute
  '/Destino': typeof DestinoIndexRoute
  '/DetallesViaje': typeof DetallesViajeIndexRoute
  '/Login': typeof LoginIndexRoute
  '/Origen': typeof OrigenIndexRoute
  '/Paradas': typeof ParadasIndexRoute
  '/Perfil': typeof PerfilIndexRoute
  '/RecuperarPasword': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo': typeof RegistrarVehiculoIndexRoute
  '/Registro': typeof RegistroIndexRoute
  '/Reservas': typeof ReservasIndexRoute
  '/Wallet': typeof WalletIndexRoute
  '/account': typeof AccountIndexRoute
  '/ayuda': typeof AyudaIndexRoute
  '/home': typeof HomeIndexRoute
  '/publicarviaje': typeof PublicarviajeIndexRoute
  '/reservar': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/RegistrarVehiculo/DocumentForm': typeof RegistrarVehiculoDocumentFormRoute
  '/RegistrarVehiculo/DocumentsRequired': typeof RegistrarVehiculoDocumentsRequiredRoute
  '/RegistrarVehiculo/License': typeof RegistrarVehiculoLicenseRoute
  '/RegistrarVehiculo/PropertyCard': typeof RegistrarVehiculoPropertyCardRoute
  '/RegistrarVehiculo/Soat': typeof RegistrarVehiculoSoatRoute
  '/Reservas/TripReservationModal': typeof ReservasTripReservationModalRoute
  '/Actividades': typeof ActividadesIndexRoute
  '/Chat': typeof ChatIndexRoute
  '/CompletarRegistro': typeof CompletarRegistroIndexRoute
  '/Cupones': typeof CuponesIndexRoute
  '/Cupos': typeof CuposIndexRoute
  '/CuposReservados': typeof CuposReservadosIndexRoute
  '/DateSelected': typeof DateSelectedIndexRoute
  '/Destino': typeof DestinoIndexRoute
  '/DetallesViaje': typeof DetallesViajeIndexRoute
  '/Login': typeof LoginIndexRoute
  '/Origen': typeof OrigenIndexRoute
  '/Paradas': typeof ParadasIndexRoute
  '/Perfil': typeof PerfilIndexRoute
  '/RecuperarPasword': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo': typeof RegistrarVehiculoIndexRoute
  '/Registro': typeof RegistroIndexRoute
  '/Reservas': typeof ReservasIndexRoute
  '/Wallet': typeof WalletIndexRoute
  '/account': typeof AccountIndexRoute
  '/ayuda': typeof AyudaIndexRoute
  '/home': typeof HomeIndexRoute
  '/publicarviaje': typeof PublicarviajeIndexRoute
  '/reservar': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/RegistrarVehiculo/DocumentForm': typeof RegistrarVehiculoDocumentFormRoute
  '/RegistrarVehiculo/DocumentsRequired': typeof RegistrarVehiculoDocumentsRequiredRoute
  '/RegistrarVehiculo/License': typeof RegistrarVehiculoLicenseRoute
  '/RegistrarVehiculo/PropertyCard': typeof RegistrarVehiculoPropertyCardRoute
  '/RegistrarVehiculo/Soat': typeof RegistrarVehiculoSoatRoute
  '/Reservas/TripReservationModal': typeof ReservasTripReservationModalRoute
  '/Actividades/': typeof ActividadesIndexRoute
  '/Chat/': typeof ChatIndexRoute
  '/CompletarRegistro/': typeof CompletarRegistroIndexRoute
  '/Cupones/': typeof CuponesIndexRoute
  '/Cupos/': typeof CuposIndexRoute
  '/CuposReservados/': typeof CuposReservadosIndexRoute
  '/DateSelected/': typeof DateSelectedIndexRoute
  '/Destino/': typeof DestinoIndexRoute
  '/DetallesViaje/': typeof DetallesViajeIndexRoute
  '/Login/': typeof LoginIndexRoute
  '/Origen/': typeof OrigenIndexRoute
  '/Paradas/': typeof ParadasIndexRoute
  '/Perfil/': typeof PerfilIndexRoute
  '/RecuperarPasword/': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo/': typeof RegistrarVehiculoIndexRoute
  '/Registro/': typeof RegistroIndexRoute
  '/Reservas/': typeof ReservasIndexRoute
  '/Wallet/': typeof WalletIndexRoute
  '/account/': typeof AccountIndexRoute
  '/ayuda/': typeof AyudaIndexRoute
  '/home/': typeof HomeIndexRoute
  '/publicarviaje/': typeof PublicarviajeIndexRoute
  '/reservar/': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/RegistrarVehiculo/DocumentForm'
    | '/RegistrarVehiculo/DocumentsRequired'
    | '/RegistrarVehiculo/License'
    | '/RegistrarVehiculo/PropertyCard'
    | '/RegistrarVehiculo/Soat'
    | '/Reservas/TripReservationModal'
    | '/Actividades'
    | '/Chat'
    | '/CompletarRegistro'
    | '/Cupones'
    | '/Cupos'
    | '/CuposReservados'
    | '/DateSelected'
    | '/Destino'
    | '/DetallesViaje'
    | '/Login'
    | '/Origen'
    | '/Paradas'
    | '/Perfil'
    | '/RecuperarPasword'
    | '/RegistrarVehiculo'
    | '/Registro'
    | '/Reservas'
    | '/Wallet'
    | '/account'
    | '/ayuda'
    | '/home'
    | '/publicarviaje'
    | '/reservar'
    | '/CardStars/cardGreen'
    | '/CuposReservados/ValidarCupo/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/RegistrarVehiculo/DocumentForm'
    | '/RegistrarVehiculo/DocumentsRequired'
    | '/RegistrarVehiculo/License'
    | '/RegistrarVehiculo/PropertyCard'
    | '/RegistrarVehiculo/Soat'
    | '/Reservas/TripReservationModal'
    | '/Actividades'
    | '/Chat'
    | '/CompletarRegistro'
    | '/Cupones'
    | '/Cupos'
    | '/CuposReservados'
    | '/DateSelected'
    | '/Destino'
    | '/DetallesViaje'
    | '/Login'
    | '/Origen'
    | '/Paradas'
    | '/Perfil'
    | '/RecuperarPasword'
    | '/RegistrarVehiculo'
    | '/Registro'
    | '/Reservas'
    | '/Wallet'
    | '/account'
    | '/ayuda'
    | '/home'
    | '/publicarviaje'
    | '/reservar'
    | '/CuposReservados/ValidarCupo/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/RegistrarVehiculo/DocumentForm'
    | '/RegistrarVehiculo/DocumentsRequired'
    | '/RegistrarVehiculo/License'
    | '/RegistrarVehiculo/PropertyCard'
    | '/RegistrarVehiculo/Soat'
    | '/Reservas/TripReservationModal'
    | '/Actividades/'
    | '/Chat/'
    | '/CompletarRegistro/'
    | '/Cupones/'
    | '/Cupos/'
    | '/CuposReservados/'
    | '/DateSelected/'
    | '/Destino/'
    | '/DetallesViaje/'
    | '/Login/'
    | '/Origen/'
    | '/Paradas/'
    | '/Perfil/'
    | '/RecuperarPasword/'
    | '/RegistrarVehiculo/'
    | '/Registro/'
    | '/Reservas/'
    | '/Wallet/'
    | '/account/'
    | '/ayuda/'
    | '/home/'
    | '/publicarviaje/'
    | '/reservar/'
    | '/CuposReservados/ValidarCupo/$bookingId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ActividadesActividadesPageRoute: typeof ActividadesActividadesPageRoute
  CuposViewBookingDetailsRoute: typeof CuposViewBookingDetailsRoute
  CuposViewPassengersRoute: typeof CuposViewPassengersRoute
  CuposViewTicketRoute: typeof CuposViewTicketRoute
  RecuperarPaswordForgotPasswordRoute: typeof RecuperarPaswordForgotPasswordRoute
  RegistrarVehiculoDocumentFormRoute: typeof RegistrarVehiculoDocumentFormRoute
  RegistrarVehiculoDocumentsRequiredRoute: typeof RegistrarVehiculoDocumentsRequiredRoute
  RegistrarVehiculoLicenseRoute: typeof RegistrarVehiculoLicenseRoute
  RegistrarVehiculoPropertyCardRoute: typeof RegistrarVehiculoPropertyCardRoute
  RegistrarVehiculoSoatRoute: typeof RegistrarVehiculoSoatRoute
  ReservasTripReservationModalRoute: typeof ReservasTripReservationModalRoute
  ActividadesIndexRoute: typeof ActividadesIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  CompletarRegistroIndexRoute: typeof CompletarRegistroIndexRoute
  CuponesIndexRoute: typeof CuponesIndexRoute
  CuposIndexRoute: typeof CuposIndexRoute
  CuposReservadosIndexRoute: typeof CuposReservadosIndexRoute
  DateSelectedIndexRoute: typeof DateSelectedIndexRoute
  DestinoIndexRoute: typeof DestinoIndexRoute
  DetallesViajeIndexRoute: typeof DetallesViajeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OrigenIndexRoute: typeof OrigenIndexRoute
  ParadasIndexRoute: typeof ParadasIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  RecuperarPaswordIndexRoute: typeof RecuperarPaswordIndexRoute
  RegistrarVehiculoIndexRoute: typeof RegistrarVehiculoIndexRoute
  RegistroIndexRoute: typeof RegistroIndexRoute
  ReservasIndexRoute: typeof ReservasIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AyudaIndexRoute: typeof AyudaIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  PublicarviajeIndexRoute: typeof PublicarviajeIndexRoute
  ReservarIndexRoute: typeof ReservarIndexRoute
  CuposReservadosValidarCupoBookingIdRoute: typeof CuposReservadosValidarCupoBookingIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ActividadesActividadesPageRoute: ActividadesActividadesPageRoute,
  CuposViewBookingDetailsRoute: CuposViewBookingDetailsRoute,
  CuposViewPassengersRoute: CuposViewPassengersRoute,
  CuposViewTicketRoute: CuposViewTicketRoute,
  RecuperarPaswordForgotPasswordRoute: RecuperarPaswordForgotPasswordRoute,
  RegistrarVehiculoDocumentFormRoute: RegistrarVehiculoDocumentFormRoute,
  RegistrarVehiculoDocumentsRequiredRoute:
    RegistrarVehiculoDocumentsRequiredRoute,
  RegistrarVehiculoLicenseRoute: RegistrarVehiculoLicenseRoute,
  RegistrarVehiculoPropertyCardRoute: RegistrarVehiculoPropertyCardRoute,
  RegistrarVehiculoSoatRoute: RegistrarVehiculoSoatRoute,
  ReservasTripReservationModalRoute: ReservasTripReservationModalRoute,
  ActividadesIndexRoute: ActividadesIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  CompletarRegistroIndexRoute: CompletarRegistroIndexRoute,
  CuponesIndexRoute: CuponesIndexRoute,
  CuposIndexRoute: CuposIndexRoute,
  CuposReservadosIndexRoute: CuposReservadosIndexRoute,
  DateSelectedIndexRoute: DateSelectedIndexRoute,
  DestinoIndexRoute: DestinoIndexRoute,
  DetallesViajeIndexRoute: DetallesViajeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OrigenIndexRoute: OrigenIndexRoute,
  ParadasIndexRoute: ParadasIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  RecuperarPaswordIndexRoute: RecuperarPaswordIndexRoute,
  RegistrarVehiculoIndexRoute: RegistrarVehiculoIndexRoute,
  RegistroIndexRoute: RegistroIndexRoute,
  ReservasIndexRoute: ReservasIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  AyudaIndexRoute: AyudaIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  PublicarviajeIndexRoute: PublicarviajeIndexRoute,
  ReservarIndexRoute: ReservarIndexRoute,
  CuposReservadosValidarCupoBookingIdRoute:
    CuposReservadosValidarCupoBookingIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Actividades/ActividadesPage",
        "/Cupos/ViewBookingDetails",
        "/Cupos/ViewPassengers",
        "/Cupos/ViewTicket",
        "/RecuperarPasword/ForgotPassword",
        "/RegistrarVehiculo/DocumentForm",
        "/RegistrarVehiculo/DocumentsRequired",
        "/RegistrarVehiculo/License",
        "/RegistrarVehiculo/PropertyCard",
        "/RegistrarVehiculo/Soat",
        "/Reservas/TripReservationModal",
        "/Actividades/",
        "/Chat/",
        "/CompletarRegistro/",
        "/Cupones/",
        "/Cupos/",
        "/CuposReservados/",
        "/DateSelected/",
        "/Destino/",
        "/DetallesViaje/",
        "/Login/",
        "/Origen/",
        "/Paradas/",
        "/Perfil/",
        "/RecuperarPasword/",
        "/RegistrarVehiculo/",
        "/Registro/",
        "/Reservas/",
        "/Wallet/",
        "/account/",
        "/ayuda/",
        "/home/",
        "/publicarviaje/",
        "/reservar/",
        "/CuposReservados/ValidarCupo/$bookingId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/Actividades/ActividadesPage": {
      "filePath": "Actividades/ActividadesPage.tsx"
    },
    "/Cupos/ViewBookingDetails": {
      "filePath": "Cupos/ViewBookingDetails.tsx"
    },
    "/Cupos/ViewPassengers": {
      "filePath": "Cupos/ViewPassengers.tsx"
    },
    "/Cupos/ViewTicket": {
      "filePath": "Cupos/ViewTicket.tsx"
    },
    "/RecuperarPasword/ForgotPassword": {
      "filePath": "RecuperarPasword/ForgotPassword.tsx"
    },
    "/RegistrarVehiculo/DocumentForm": {
      "filePath": "RegistrarVehiculo/DocumentForm.tsx"
    },
    "/RegistrarVehiculo/DocumentsRequired": {
      "filePath": "RegistrarVehiculo/DocumentsRequired.tsx"
    },
    "/RegistrarVehiculo/License": {
      "filePath": "RegistrarVehiculo/License.tsx"
    },
    "/RegistrarVehiculo/PropertyCard": {
      "filePath": "RegistrarVehiculo/PropertyCard.tsx"
    },
    "/RegistrarVehiculo/Soat": {
      "filePath": "RegistrarVehiculo/Soat.tsx"
    },
    "/Reservas/TripReservationModal": {
      "filePath": "Reservas/TripReservationModal.tsx"
    },
    "/Actividades/": {
      "filePath": "Actividades/index.tsx"
    },
    "/Chat/": {
      "filePath": "Chat/index.tsx"
    },
    "/CompletarRegistro/": {
      "filePath": "CompletarRegistro/index.tsx"
    },
    "/Cupones/": {
      "filePath": "Cupones/index.tsx"
    },
    "/Cupos/": {
      "filePath": "Cupos/index.tsx"
    },
    "/CuposReservados/": {
      "filePath": "CuposReservados/index.tsx"
    },
    "/DateSelected/": {
      "filePath": "DateSelected/index.tsx"
    },
    "/Destino/": {
      "filePath": "Destino/index.tsx"
    },
    "/DetallesViaje/": {
      "filePath": "DetallesViaje/index.tsx"
    },
    "/Login/": {
      "filePath": "Login/index.tsx"
    },
    "/Origen/": {
      "filePath": "Origen/index.tsx"
    },
    "/Paradas/": {
      "filePath": "Paradas/index.tsx"
    },
    "/Perfil/": {
      "filePath": "Perfil/index.tsx"
    },
    "/RecuperarPasword/": {
      "filePath": "RecuperarPasword/index.tsx"
    },
    "/RegistrarVehiculo/": {
      "filePath": "RegistrarVehiculo/index.tsx"
    },
    "/Registro/": {
      "filePath": "Registro/index.tsx"
    },
    "/Reservas/": {
      "filePath": "Reservas/index.tsx"
    },
    "/Wallet/": {
      "filePath": "Wallet/index.tsx"
    },
    "/account/": {
      "filePath": "account/index.tsx"
    },
    "/ayuda/": {
      "filePath": "ayuda/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/publicarviaje/": {
      "filePath": "publicarviaje/index.tsx"
    },
    "/reservar/": {
      "filePath": "reservar/index.tsx"
    },
    "/CuposReservados/ValidarCupo/$bookingId": {
      "filePath": "CuposReservados/ValidarCupo.$bookingId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
