/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservarIndexRouteImport } from './routes/reservar/index'
import { Route as PublicarviajeIndexRouteImport } from './routes/publicarviaje/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ChangeIndexRouteImport } from './routes/change/index'
import { Route as AyudaIndexRouteImport } from './routes/ayuda/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as WalletIndexRouteImport } from './routes/Wallet/index'
import { Route as ReservasIndexRouteImport } from './routes/Reservas/index'
import { Route as RegistroIndexRouteImport } from './routes/Registro/index'
import { Route as RegistrarVehiculoIndexRouteImport } from './routes/RegistrarVehiculo/index'
import { Route as RecuperarPaswordIndexRouteImport } from './routes/RecuperarPasword/index'
import { Route as PerfilIndexRouteImport } from './routes/Perfil/index'
import { Route as ParadasIndexRouteImport } from './routes/Paradas/index'
import { Route as OrigenIndexRouteImport } from './routes/Origen/index'
import { Route as LoginIndexRouteImport } from './routes/Login/index'
import { Route as DetallesViajeIndexRouteImport } from './routes/DetallesViaje/index'
import { Route as DestinoIndexRouteImport } from './routes/Destino/index'
import { Route as DateSelectedIndexRouteImport } from './routes/DateSelected/index'
import { Route as CuposReservadosIndexRouteImport } from './routes/CuposReservados/index'
import { Route as CuposIndexRouteImport } from './routes/Cupos/index'
import { Route as CuponesIndexRouteImport } from './routes/Cupones/index'
import { Route as CompletarRegistroIndexRouteImport } from './routes/CompletarRegistro/index'
import { Route as ChatIndexRouteImport } from './routes/Chat/index'
import { Route as ActividadesIndexRouteImport } from './routes/Actividades/index'
import { Route as ReservasTripReservationModalRouteImport } from './routes/Reservas/TripReservationModal'
import { Route as RegistrarVehiculoSoatRouteImport } from './routes/RegistrarVehiculo/Soat'
import { Route as RegistrarVehiculoPropertyCardRouteImport } from './routes/RegistrarVehiculo/PropertyCard'
import { Route as RegistrarVehiculoLicenseRouteImport } from './routes/RegistrarVehiculo/License'
import { Route as RegistrarVehiculoDocumentsRequiredRouteImport } from './routes/RegistrarVehiculo/DocumentsRequired'
import { Route as RegistrarVehiculoDocumentFormRouteImport } from './routes/RegistrarVehiculo/DocumentForm'
import { Route as RecuperarPaswordForgotPasswordRouteImport } from './routes/RecuperarPasword/ForgotPassword'
import { Route as CuposViewTicketRouteImport } from './routes/Cupos/ViewTicket'
import { Route as CuposViewPassengersRouteImport } from './routes/Cupos/ViewPassengers'
import { Route as CuposViewBookingDetailsRouteImport } from './routes/Cupos/ViewBookingDetails'
import { Route as ActividadesActividadesPageRouteImport } from './routes/Actividades/ActividadesPage'
import { Route as CuposReservadosValidarCupoBookingIdRouteImport } from './routes/CuposReservados/ValidarCupo.$bookingId'

const IndexLazyRouteImport = createFileRoute('/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ReservarIndexRoute = ReservarIndexRouteImport.update({
  id: '/reservar/',
  path: '/reservar/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarviajeIndexRoute = PublicarviajeIndexRouteImport.update({
  id: '/publicarviaje/',
  path: '/publicarviaje/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeIndexRoute = ChangeIndexRouteImport.update({
  id: '/change/',
  path: '/change/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaIndexRoute = AyudaIndexRouteImport.update({
  id: '/ayuda/',
  path: '/ayuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/Wallet/',
  path: '/Wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasIndexRoute = ReservasIndexRouteImport.update({
  id: '/Reservas/',
  path: '/Reservas/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroIndexRoute = RegistroIndexRouteImport.update({
  id: '/Registro/',
  path: '/Registro/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarVehiculoIndexRoute = RegistrarVehiculoIndexRouteImport.update({
  id: '/RegistrarVehiculo/',
  path: '/RegistrarVehiculo/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPaswordIndexRoute = RecuperarPaswordIndexRouteImport.update({
  id: '/RecuperarPasword/',
  path: '/RecuperarPasword/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/Perfil/',
  path: '/Perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParadasIndexRoute = ParadasIndexRouteImport.update({
  id: '/Paradas/',
  path: '/Paradas/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigenIndexRoute = OrigenIndexRouteImport.update({
  id: '/Origen/',
  path: '/Origen/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/Login/',
  path: '/Login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetallesViajeIndexRoute = DetallesViajeIndexRouteImport.update({
  id: '/DetallesViaje/',
  path: '/DetallesViaje/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinoIndexRoute = DestinoIndexRouteImport.update({
  id: '/Destino/',
  path: '/Destino/',
  getParentRoute: () => rootRouteImport,
} as any)
const DateSelectedIndexRoute = DateSelectedIndexRouteImport.update({
  id: '/DateSelected/',
  path: '/DateSelected/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposReservadosIndexRoute = CuposReservadosIndexRouteImport.update({
  id: '/CuposReservados/',
  path: '/CuposReservados/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposIndexRoute = CuposIndexRouteImport.update({
  id: '/Cupos/',
  path: '/Cupos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponesIndexRoute = CuponesIndexRouteImport.update({
  id: '/Cupones/',
  path: '/Cupones/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarRegistroIndexRoute = CompletarRegistroIndexRouteImport.update({
  id: '/CompletarRegistro/',
  path: '/CompletarRegistro/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/Chat/',
  path: '/Chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesIndexRoute = ActividadesIndexRouteImport.update({
  id: '/Actividades/',
  path: '/Actividades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasTripReservationModalRoute =
  ReservasTripReservationModalRouteImport.update({
    id: '/Reservas/TripReservationModal',
    path: '/Reservas/TripReservationModal',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistrarVehiculoSoatRoute = RegistrarVehiculoSoatRouteImport.update({
  id: '/RegistrarVehiculo/Soat',
  path: '/RegistrarVehiculo/Soat',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarVehiculoPropertyCardRoute =
  RegistrarVehiculoPropertyCardRouteImport.update({
    id: '/RegistrarVehiculo/PropertyCard',
    path: '/RegistrarVehiculo/PropertyCard',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistrarVehiculoLicenseRoute =
  RegistrarVehiculoLicenseRouteImport.update({
    id: '/RegistrarVehiculo/License',
    path: '/RegistrarVehiculo/License',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistrarVehiculoDocumentsRequiredRoute =
  RegistrarVehiculoDocumentsRequiredRouteImport.update({
    id: '/RegistrarVehiculo/DocumentsRequired',
    path: '/RegistrarVehiculo/DocumentsRequired',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistrarVehiculoDocumentFormRoute =
  RegistrarVehiculoDocumentFormRouteImport.update({
    id: '/RegistrarVehiculo/DocumentForm',
    path: '/RegistrarVehiculo/DocumentForm',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecuperarPaswordForgotPasswordRoute =
  RecuperarPaswordForgotPasswordRouteImport.update({
    id: '/RecuperarPasword/ForgotPassword',
    path: '/RecuperarPasword/ForgotPassword',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuposViewTicketRoute = CuposViewTicketRouteImport.update({
  id: '/Cupos/ViewTicket',
  path: '/Cupos/ViewTicket',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposViewPassengersRoute = CuposViewPassengersRouteImport.update({
  id: '/Cupos/ViewPassengers',
  path: '/Cupos/ViewPassengers',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposViewBookingDetailsRoute = CuposViewBookingDetailsRouteImport.update({
  id: '/Cupos/ViewBookingDetails',
  path: '/Cupos/ViewBookingDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesActividadesPageRoute =
  ActividadesActividadesPageRouteImport.update({
    id: '/Actividades/ActividadesPage',
    path: '/Actividades/ActividadesPage',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuposReservadosValidarCupoBookingIdRoute =
  CuposReservadosValidarCupoBookingIdRouteImport.update({
    id: '/CuposReservados/ValidarCupo/$bookingId',
    path: '/CuposReservados/ValidarCupo/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/RegistrarVehiculo/DocumentForm': typeof RegistrarVehiculoDocumentFormRoute
  '/RegistrarVehiculo/DocumentsRequired': typeof RegistrarVehiculoDocumentsRequiredRoute
  '/RegistrarVehiculo/License': typeof RegistrarVehiculoLicenseRoute
  '/RegistrarVehiculo/PropertyCard': typeof RegistrarVehiculoPropertyCardRoute
  '/RegistrarVehiculo/Soat': typeof RegistrarVehiculoSoatRoute
  '/Reservas/TripReservationModal': typeof ReservasTripReservationModalRoute
  '/Actividades': typeof ActividadesIndexRoute
  '/Chat': typeof ChatIndexRoute
  '/CompletarRegistro': typeof CompletarRegistroIndexRoute
  '/Cupones': typeof CuponesIndexRoute
  '/Cupos': typeof CuposIndexRoute
  '/CuposReservados': typeof CuposReservadosIndexRoute
  '/DateSelected': typeof DateSelectedIndexRoute
  '/Destino': typeof DestinoIndexRoute
  '/DetallesViaje': typeof DetallesViajeIndexRoute
  '/Login': typeof LoginIndexRoute
  '/Origen': typeof OrigenIndexRoute
  '/Paradas': typeof ParadasIndexRoute
  '/Perfil': typeof PerfilIndexRoute
  '/RecuperarPasword': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo': typeof RegistrarVehiculoIndexRoute
  '/Registro': typeof RegistroIndexRoute
  '/Reservas': typeof ReservasIndexRoute
  '/Wallet': typeof WalletIndexRoute
  '/account': typeof AccountIndexRoute
  '/ayuda': typeof AyudaIndexRoute
  '/change': typeof ChangeIndexRoute
  '/home': typeof HomeIndexRoute
  '/publicarviaje': typeof PublicarviajeIndexRoute
  '/reservar': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/RegistrarVehiculo/DocumentForm': typeof RegistrarVehiculoDocumentFormRoute
  '/RegistrarVehiculo/DocumentsRequired': typeof RegistrarVehiculoDocumentsRequiredRoute
  '/RegistrarVehiculo/License': typeof RegistrarVehiculoLicenseRoute
  '/RegistrarVehiculo/PropertyCard': typeof RegistrarVehiculoPropertyCardRoute
  '/RegistrarVehiculo/Soat': typeof RegistrarVehiculoSoatRoute
  '/Reservas/TripReservationModal': typeof ReservasTripReservationModalRoute
  '/Actividades': typeof ActividadesIndexRoute
  '/Chat': typeof ChatIndexRoute
  '/CompletarRegistro': typeof CompletarRegistroIndexRoute
  '/Cupones': typeof CuponesIndexRoute
  '/Cupos': typeof CuposIndexRoute
  '/CuposReservados': typeof CuposReservadosIndexRoute
  '/DateSelected': typeof DateSelectedIndexRoute
  '/Destino': typeof DestinoIndexRoute
  '/DetallesViaje': typeof DetallesViajeIndexRoute
  '/Login': typeof LoginIndexRoute
  '/Origen': typeof OrigenIndexRoute
  '/Paradas': typeof ParadasIndexRoute
  '/Perfil': typeof PerfilIndexRoute
  '/RecuperarPasword': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo': typeof RegistrarVehiculoIndexRoute
  '/Registro': typeof RegistroIndexRoute
  '/Reservas': typeof ReservasIndexRoute
  '/Wallet': typeof WalletIndexRoute
  '/account': typeof AccountIndexRoute
  '/ayuda': typeof AyudaIndexRoute
  '/change': typeof ChangeIndexRoute
  '/home': typeof HomeIndexRoute
  '/publicarviaje': typeof PublicarviajeIndexRoute
  '/reservar': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/RegistrarVehiculo/DocumentForm': typeof RegistrarVehiculoDocumentFormRoute
  '/RegistrarVehiculo/DocumentsRequired': typeof RegistrarVehiculoDocumentsRequiredRoute
  '/RegistrarVehiculo/License': typeof RegistrarVehiculoLicenseRoute
  '/RegistrarVehiculo/PropertyCard': typeof RegistrarVehiculoPropertyCardRoute
  '/RegistrarVehiculo/Soat': typeof RegistrarVehiculoSoatRoute
  '/Reservas/TripReservationModal': typeof ReservasTripReservationModalRoute
  '/Actividades/': typeof ActividadesIndexRoute
  '/Chat/': typeof ChatIndexRoute
  '/CompletarRegistro/': typeof CompletarRegistroIndexRoute
  '/Cupones/': typeof CuponesIndexRoute
  '/Cupos/': typeof CuposIndexRoute
  '/CuposReservados/': typeof CuposReservadosIndexRoute
  '/DateSelected/': typeof DateSelectedIndexRoute
  '/Destino/': typeof DestinoIndexRoute
  '/DetallesViaje/': typeof DetallesViajeIndexRoute
  '/Login/': typeof LoginIndexRoute
  '/Origen/': typeof OrigenIndexRoute
  '/Paradas/': typeof ParadasIndexRoute
  '/Perfil/': typeof PerfilIndexRoute
  '/RecuperarPasword/': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo/': typeof RegistrarVehiculoIndexRoute
  '/Registro/': typeof RegistroIndexRoute
  '/Reservas/': typeof ReservasIndexRoute
  '/Wallet/': typeof WalletIndexRoute
  '/account/': typeof AccountIndexRoute
  '/ayuda/': typeof AyudaIndexRoute
  '/change/': typeof ChangeIndexRoute
  '/home/': typeof HomeIndexRoute
  '/publicarviaje/': typeof PublicarviajeIndexRoute
  '/reservar/': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/RegistrarVehiculo/DocumentForm'
    | '/RegistrarVehiculo/DocumentsRequired'
    | '/RegistrarVehiculo/License'
    | '/RegistrarVehiculo/PropertyCard'
    | '/RegistrarVehiculo/Soat'
    | '/Reservas/TripReservationModal'
    | '/Actividades'
    | '/Chat'
    | '/CompletarRegistro'
    | '/Cupones'
    | '/Cupos'
    | '/CuposReservados'
    | '/DateSelected'
    | '/Destino'
    | '/DetallesViaje'
    | '/Login'
    | '/Origen'
    | '/Paradas'
    | '/Perfil'
    | '/RecuperarPasword'
    | '/RegistrarVehiculo'
    | '/Registro'
    | '/Reservas'
    | '/Wallet'
    | '/account'
    | '/ayuda'
    | '/change'
    | '/home'
    | '/publicarviaje'
    | '/reservar'
    | '/CuposReservados/ValidarCupo/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/RegistrarVehiculo/DocumentForm'
    | '/RegistrarVehiculo/DocumentsRequired'
    | '/RegistrarVehiculo/License'
    | '/RegistrarVehiculo/PropertyCard'
    | '/RegistrarVehiculo/Soat'
    | '/Reservas/TripReservationModal'
    | '/Actividades'
    | '/Chat'
    | '/CompletarRegistro'
    | '/Cupones'
    | '/Cupos'
    | '/CuposReservados'
    | '/DateSelected'
    | '/Destino'
    | '/DetallesViaje'
    | '/Login'
    | '/Origen'
    | '/Paradas'
    | '/Perfil'
    | '/RecuperarPasword'
    | '/RegistrarVehiculo'
    | '/Registro'
    | '/Reservas'
    | '/Wallet'
    | '/account'
    | '/ayuda'
    | '/change'
    | '/home'
    | '/publicarviaje'
    | '/reservar'
    | '/CuposReservados/ValidarCupo/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/RegistrarVehiculo/DocumentForm'
    | '/RegistrarVehiculo/DocumentsRequired'
    | '/RegistrarVehiculo/License'
    | '/RegistrarVehiculo/PropertyCard'
    | '/RegistrarVehiculo/Soat'
    | '/Reservas/TripReservationModal'
    | '/Actividades/'
    | '/Chat/'
    | '/CompletarRegistro/'
    | '/Cupones/'
    | '/Cupos/'
    | '/CuposReservados/'
    | '/DateSelected/'
    | '/Destino/'
    | '/DetallesViaje/'
    | '/Login/'
    | '/Origen/'
    | '/Paradas/'
    | '/Perfil/'
    | '/RecuperarPasword/'
    | '/RegistrarVehiculo/'
    | '/Registro/'
    | '/Reservas/'
    | '/Wallet/'
    | '/account/'
    | '/ayuda/'
    | '/change/'
    | '/home/'
    | '/publicarviaje/'
    | '/reservar/'
    | '/CuposReservados/ValidarCupo/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ActividadesActividadesPageRoute: typeof ActividadesActividadesPageRoute
  CuposViewBookingDetailsRoute: typeof CuposViewBookingDetailsRoute
  CuposViewPassengersRoute: typeof CuposViewPassengersRoute
  CuposViewTicketRoute: typeof CuposViewTicketRoute
  RecuperarPaswordForgotPasswordRoute: typeof RecuperarPaswordForgotPasswordRoute
  RegistrarVehiculoDocumentFormRoute: typeof RegistrarVehiculoDocumentFormRoute
  RegistrarVehiculoDocumentsRequiredRoute: typeof RegistrarVehiculoDocumentsRequiredRoute
  RegistrarVehiculoLicenseRoute: typeof RegistrarVehiculoLicenseRoute
  RegistrarVehiculoPropertyCardRoute: typeof RegistrarVehiculoPropertyCardRoute
  RegistrarVehiculoSoatRoute: typeof RegistrarVehiculoSoatRoute
  ReservasTripReservationModalRoute: typeof ReservasTripReservationModalRoute
  ActividadesIndexRoute: typeof ActividadesIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  CompletarRegistroIndexRoute: typeof CompletarRegistroIndexRoute
  CuponesIndexRoute: typeof CuponesIndexRoute
  CuposIndexRoute: typeof CuposIndexRoute
  CuposReservadosIndexRoute: typeof CuposReservadosIndexRoute
  DateSelectedIndexRoute: typeof DateSelectedIndexRoute
  DestinoIndexRoute: typeof DestinoIndexRoute
  DetallesViajeIndexRoute: typeof DetallesViajeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OrigenIndexRoute: typeof OrigenIndexRoute
  ParadasIndexRoute: typeof ParadasIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  RecuperarPaswordIndexRoute: typeof RecuperarPaswordIndexRoute
  RegistrarVehiculoIndexRoute: typeof RegistrarVehiculoIndexRoute
  RegistroIndexRoute: typeof RegistroIndexRoute
  ReservasIndexRoute: typeof ReservasIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AyudaIndexRoute: typeof AyudaIndexRoute
  ChangeIndexRoute: typeof ChangeIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  PublicarviajeIndexRoute: typeof PublicarviajeIndexRoute
  ReservarIndexRoute: typeof ReservarIndexRoute
  CuposReservadosValidarCupoBookingIdRoute: typeof CuposReservadosValidarCupoBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar/': {
      id: '/reservar/'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/': {
      id: '/publicarviaje/'
      path: '/publicarviaje'
      fullPath: '/publicarviaje'
      preLoaderRoute: typeof PublicarviajeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change/': {
      id: '/change/'
      path: '/change'
      fullPath: '/change'
      preLoaderRoute: typeof ChangeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/': {
      id: '/ayuda/'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Wallet/': {
      id: '/Wallet/'
      path: '/Wallet'
      fullPath: '/Wallet'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reservas/': {
      id: '/Reservas/'
      path: '/Reservas'
      fullPath: '/Reservas'
      preLoaderRoute: typeof ReservasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Registro/': {
      id: '/Registro/'
      path: '/Registro'
      fullPath: '/Registro'
      preLoaderRoute: typeof RegistroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrarVehiculo/': {
      id: '/RegistrarVehiculo/'
      path: '/RegistrarVehiculo'
      fullPath: '/RegistrarVehiculo'
      preLoaderRoute: typeof RegistrarVehiculoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RecuperarPasword/': {
      id: '/RecuperarPasword/'
      path: '/RecuperarPasword'
      fullPath: '/RecuperarPasword'
      preLoaderRoute: typeof RecuperarPaswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Perfil/': {
      id: '/Perfil/'
      path: '/Perfil'
      fullPath: '/Perfil'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Paradas/': {
      id: '/Paradas/'
      path: '/Paradas'
      fullPath: '/Paradas'
      preLoaderRoute: typeof ParadasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Origen/': {
      id: '/Origen/'
      path: '/Origen'
      fullPath: '/Origen'
      preLoaderRoute: typeof OrigenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login/': {
      id: '/Login/'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DetallesViaje/': {
      id: '/DetallesViaje/'
      path: '/DetallesViaje'
      fullPath: '/DetallesViaje'
      preLoaderRoute: typeof DetallesViajeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Destino/': {
      id: '/Destino/'
      path: '/Destino'
      fullPath: '/Destino'
      preLoaderRoute: typeof DestinoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DateSelected/': {
      id: '/DateSelected/'
      path: '/DateSelected'
      fullPath: '/DateSelected'
      preLoaderRoute: typeof DateSelectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CuposReservados/': {
      id: '/CuposReservados/'
      path: '/CuposReservados'
      fullPath: '/CuposReservados'
      preLoaderRoute: typeof CuposReservadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupos/': {
      id: '/Cupos/'
      path: '/Cupos'
      fullPath: '/Cupos'
      preLoaderRoute: typeof CuposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupones/': {
      id: '/Cupones/'
      path: '/Cupones'
      fullPath: '/Cupones'
      preLoaderRoute: typeof CuponesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CompletarRegistro/': {
      id: '/CompletarRegistro/'
      path: '/CompletarRegistro'
      fullPath: '/CompletarRegistro'
      preLoaderRoute: typeof CompletarRegistroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Chat/': {
      id: '/Chat/'
      path: '/Chat'
      fullPath: '/Chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Actividades/': {
      id: '/Actividades/'
      path: '/Actividades'
      fullPath: '/Actividades'
      preLoaderRoute: typeof ActividadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reservas/TripReservationModal': {
      id: '/Reservas/TripReservationModal'
      path: '/Reservas/TripReservationModal'
      fullPath: '/Reservas/TripReservationModal'
      preLoaderRoute: typeof ReservasTripReservationModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrarVehiculo/Soat': {
      id: '/RegistrarVehiculo/Soat'
      path: '/RegistrarVehiculo/Soat'
      fullPath: '/RegistrarVehiculo/Soat'
      preLoaderRoute: typeof RegistrarVehiculoSoatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrarVehiculo/PropertyCard': {
      id: '/RegistrarVehiculo/PropertyCard'
      path: '/RegistrarVehiculo/PropertyCard'
      fullPath: '/RegistrarVehiculo/PropertyCard'
      preLoaderRoute: typeof RegistrarVehiculoPropertyCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrarVehiculo/License': {
      id: '/RegistrarVehiculo/License'
      path: '/RegistrarVehiculo/License'
      fullPath: '/RegistrarVehiculo/License'
      preLoaderRoute: typeof RegistrarVehiculoLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrarVehiculo/DocumentsRequired': {
      id: '/RegistrarVehiculo/DocumentsRequired'
      path: '/RegistrarVehiculo/DocumentsRequired'
      fullPath: '/RegistrarVehiculo/DocumentsRequired'
      preLoaderRoute: typeof RegistrarVehiculoDocumentsRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrarVehiculo/DocumentForm': {
      id: '/RegistrarVehiculo/DocumentForm'
      path: '/RegistrarVehiculo/DocumentForm'
      fullPath: '/RegistrarVehiculo/DocumentForm'
      preLoaderRoute: typeof RegistrarVehiculoDocumentFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RecuperarPasword/ForgotPassword': {
      id: '/RecuperarPasword/ForgotPassword'
      path: '/RecuperarPasword/ForgotPassword'
      fullPath: '/RecuperarPasword/ForgotPassword'
      preLoaderRoute: typeof RecuperarPaswordForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupos/ViewTicket': {
      id: '/Cupos/ViewTicket'
      path: '/Cupos/ViewTicket'
      fullPath: '/Cupos/ViewTicket'
      preLoaderRoute: typeof CuposViewTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupos/ViewPassengers': {
      id: '/Cupos/ViewPassengers'
      path: '/Cupos/ViewPassengers'
      fullPath: '/Cupos/ViewPassengers'
      preLoaderRoute: typeof CuposViewPassengersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupos/ViewBookingDetails': {
      id: '/Cupos/ViewBookingDetails'
      path: '/Cupos/ViewBookingDetails'
      fullPath: '/Cupos/ViewBookingDetails'
      preLoaderRoute: typeof CuposViewBookingDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Actividades/ActividadesPage': {
      id: '/Actividades/ActividadesPage'
      path: '/Actividades/ActividadesPage'
      fullPath: '/Actividades/ActividadesPage'
      preLoaderRoute: typeof ActividadesActividadesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CuposReservados/ValidarCupo/$bookingId': {
      id: '/CuposReservados/ValidarCupo/$bookingId'
      path: '/CuposReservados/ValidarCupo/$bookingId'
      fullPath: '/CuposReservados/ValidarCupo/$bookingId'
      preLoaderRoute: typeof CuposReservadosValidarCupoBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ActividadesActividadesPageRoute: ActividadesActividadesPageRoute,
  CuposViewBookingDetailsRoute: CuposViewBookingDetailsRoute,
  CuposViewPassengersRoute: CuposViewPassengersRoute,
  CuposViewTicketRoute: CuposViewTicketRoute,
  RecuperarPaswordForgotPasswordRoute: RecuperarPaswordForgotPasswordRoute,
  RegistrarVehiculoDocumentFormRoute: RegistrarVehiculoDocumentFormRoute,
  RegistrarVehiculoDocumentsRequiredRoute:
    RegistrarVehiculoDocumentsRequiredRoute,
  RegistrarVehiculoLicenseRoute: RegistrarVehiculoLicenseRoute,
  RegistrarVehiculoPropertyCardRoute: RegistrarVehiculoPropertyCardRoute,
  RegistrarVehiculoSoatRoute: RegistrarVehiculoSoatRoute,
  ReservasTripReservationModalRoute: ReservasTripReservationModalRoute,
  ActividadesIndexRoute: ActividadesIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  CompletarRegistroIndexRoute: CompletarRegistroIndexRoute,
  CuponesIndexRoute: CuponesIndexRoute,
  CuposIndexRoute: CuposIndexRoute,
  CuposReservadosIndexRoute: CuposReservadosIndexRoute,
  DateSelectedIndexRoute: DateSelectedIndexRoute,
  DestinoIndexRoute: DestinoIndexRoute,
  DetallesViajeIndexRoute: DetallesViajeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OrigenIndexRoute: OrigenIndexRoute,
  ParadasIndexRoute: ParadasIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  RecuperarPaswordIndexRoute: RecuperarPaswordIndexRoute,
  RegistrarVehiculoIndexRoute: RegistrarVehiculoIndexRoute,
  RegistroIndexRoute: RegistroIndexRoute,
  ReservasIndexRoute: ReservasIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  AyudaIndexRoute: AyudaIndexRoute,
  ChangeIndexRoute: ChangeIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  PublicarviajeIndexRoute: PublicarviajeIndexRoute,
  ReservarIndexRoute: ReservarIndexRoute,
  CuposReservadosValidarCupoBookingIdRoute:
    CuposReservadosValidarCupoBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
