/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservarIndexRouteImport } from './routes/reservar/index'
import { Route as PublicarviajeIndexRouteImport } from './routes/publicarviaje/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ChangeIndexRouteImport } from './routes/change/index'
import { Route as AyudaIndexRouteImport } from './routes/ayuda/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as WalletIndexRouteImport } from './routes/Wallet/index'
import { Route as SafePointsIndexRouteImport } from './routes/SafePoints/index'
import { Route as ReservasIndexRouteImport } from './routes/Reservas/index'
import { Route as RegistroIndexRouteImport } from './routes/Registro/index'
import { Route as RegistrarVehiculoIndexRouteImport } from './routes/RegistrarVehiculo/index'
import { Route as RecuperarPaswordIndexRouteImport } from './routes/RecuperarPasword/index'
import { Route as PerfilIndexRouteImport } from './routes/Perfil/index'
import { Route as LoginIndexRouteImport } from './routes/Login/index'
import { Route as DateSelectedIndexRouteImport } from './routes/DateSelected/index'
import { Route as CuposReservadosIndexRouteImport } from './routes/CuposReservados/index'
import { Route as CuposIndexRouteImport } from './routes/Cupos/index'
import { Route as CuponesIndexRouteImport } from './routes/Cupones/index'
import { Route as CompletarRegistroIndexRouteImport } from './routes/CompletarRegistro/index'
import { Route as ChatIndexRouteImport } from './routes/Chat/index'
import { Route as ActividadesIndexRouteImport } from './routes/Actividades/index'
import { Route as RecuperarPaswordForgotPasswordRouteImport } from './routes/RecuperarPasword/ForgotPassword'
import { Route as CuposViewTicketRouteImport } from './routes/Cupos/ViewTicket'
import { Route as CuposViewPassengersRouteImport } from './routes/Cupos/ViewPassengers'
import { Route as CuposViewBookingDetailsRouteImport } from './routes/Cupos/ViewBookingDetails'
import { Route as ActividadesActividadesPageRouteImport } from './routes/Actividades/ActividadesPage'
import { Route as PublicarviajeVehiculoPreferenciasIndexRouteImport } from './routes/publicarviaje/vehiculo-preferencias/index'
import { Route as PublicarviajeRutasIndexRouteImport } from './routes/publicarviaje/rutas/index'
import { Route as PublicarviajeResumenConfirmacionIndexRouteImport } from './routes/publicarviaje/resumen-confirmacion/index'
import { Route as PublicarviajePuntosDescensoIndexRouteImport } from './routes/publicarviaje/puntos-descenso/index'
import { Route as PublicarviajePuntoRecogidaIndexRouteImport } from './routes/publicarviaje/punto-recogida/index'
import { Route as PublicarviajeFechaHoraIndexRouteImport } from './routes/publicarviaje/fecha-hora/index'
import { Route as PublicarviajeAsientosPrecioIndexRouteImport } from './routes/publicarviaje/asientos-precio/index'
import { Route as PublicarviajeParadasIndexRouteImport } from './routes/publicarviaje/Paradas/index'
import { Route as PublicarviajeOrigenIndexRouteImport } from './routes/publicarviaje/Origen/index'
import { Route as PublicarviajeDetallesViajeIndexRouteImport } from './routes/publicarviaje/DetallesViaje/index'
import { Route as PublicarviajeDestinoIndexRouteImport } from './routes/publicarviaje/Destino/index'
import { Route as CuposReservadosValidarCupoBookingIdRouteImport } from './routes/CuposReservados/ValidarCupo.$bookingId'

const IndexLazyRouteImport = createFileRoute('/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ReservarIndexRoute = ReservarIndexRouteImport.update({
  id: '/reservar/',
  path: '/reservar/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarviajeIndexRoute = PublicarviajeIndexRouteImport.update({
  id: '/publicarviaje/',
  path: '/publicarviaje/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeIndexRoute = ChangeIndexRouteImport.update({
  id: '/change/',
  path: '/change/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaIndexRoute = AyudaIndexRouteImport.update({
  id: '/ayuda/',
  path: '/ayuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/Wallet/',
  path: '/Wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafePointsIndexRoute = SafePointsIndexRouteImport.update({
  id: '/SafePoints/',
  path: '/SafePoints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasIndexRoute = ReservasIndexRouteImport.update({
  id: '/Reservas/',
  path: '/Reservas/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroIndexRoute = RegistroIndexRouteImport.update({
  id: '/Registro/',
  path: '/Registro/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarVehiculoIndexRoute = RegistrarVehiculoIndexRouteImport.update({
  id: '/RegistrarVehiculo/',
  path: '/RegistrarVehiculo/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPaswordIndexRoute = RecuperarPaswordIndexRouteImport.update({
  id: '/RecuperarPasword/',
  path: '/RecuperarPasword/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/Perfil/',
  path: '/Perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/Login/',
  path: '/Login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DateSelectedIndexRoute = DateSelectedIndexRouteImport.update({
  id: '/DateSelected/',
  path: '/DateSelected/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposReservadosIndexRoute = CuposReservadosIndexRouteImport.update({
  id: '/CuposReservados/',
  path: '/CuposReservados/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposIndexRoute = CuposIndexRouteImport.update({
  id: '/Cupos/',
  path: '/Cupos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponesIndexRoute = CuponesIndexRouteImport.update({
  id: '/Cupones/',
  path: '/Cupones/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarRegistroIndexRoute = CompletarRegistroIndexRouteImport.update({
  id: '/CompletarRegistro/',
  path: '/CompletarRegistro/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/Chat/',
  path: '/Chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesIndexRoute = ActividadesIndexRouteImport.update({
  id: '/Actividades/',
  path: '/Actividades/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPaswordForgotPasswordRoute =
  RecuperarPaswordForgotPasswordRouteImport.update({
    id: '/RecuperarPasword/ForgotPassword',
    path: '/RecuperarPasword/ForgotPassword',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuposViewTicketRoute = CuposViewTicketRouteImport.update({
  id: '/Cupos/ViewTicket',
  path: '/Cupos/ViewTicket',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposViewPassengersRoute = CuposViewPassengersRouteImport.update({
  id: '/Cupos/ViewPassengers',
  path: '/Cupos/ViewPassengers',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposViewBookingDetailsRoute = CuposViewBookingDetailsRouteImport.update({
  id: '/Cupos/ViewBookingDetails',
  path: '/Cupos/ViewBookingDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesActividadesPageRoute =
  ActividadesActividadesPageRouteImport.update({
    id: '/Actividades/ActividadesPage',
    path: '/Actividades/ActividadesPage',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajeVehiculoPreferenciasIndexRoute =
  PublicarviajeVehiculoPreferenciasIndexRouteImport.update({
    id: '/publicarviaje/vehiculo-preferencias/',
    path: '/publicarviaje/vehiculo-preferencias/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajeRutasIndexRoute = PublicarviajeRutasIndexRouteImport.update({
  id: '/publicarviaje/rutas/',
  path: '/publicarviaje/rutas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarviajeResumenConfirmacionIndexRoute =
  PublicarviajeResumenConfirmacionIndexRouteImport.update({
    id: '/publicarviaje/resumen-confirmacion/',
    path: '/publicarviaje/resumen-confirmacion/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajePuntosDescensoIndexRoute =
  PublicarviajePuntosDescensoIndexRouteImport.update({
    id: '/publicarviaje/puntos-descenso/',
    path: '/publicarviaje/puntos-descenso/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajePuntoRecogidaIndexRoute =
  PublicarviajePuntoRecogidaIndexRouteImport.update({
    id: '/publicarviaje/punto-recogida/',
    path: '/publicarviaje/punto-recogida/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajeFechaHoraIndexRoute =
  PublicarviajeFechaHoraIndexRouteImport.update({
    id: '/publicarviaje/fecha-hora/',
    path: '/publicarviaje/fecha-hora/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajeAsientosPrecioIndexRoute =
  PublicarviajeAsientosPrecioIndexRouteImport.update({
    id: '/publicarviaje/asientos-precio/',
    path: '/publicarviaje/asientos-precio/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajeParadasIndexRoute =
  PublicarviajeParadasIndexRouteImport.update({
    id: '/publicarviaje/Paradas/',
    path: '/publicarviaje/Paradas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajeOrigenIndexRoute =
  PublicarviajeOrigenIndexRouteImport.update({
    id: '/publicarviaje/Origen/',
    path: '/publicarviaje/Origen/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajeDetallesViajeIndexRoute =
  PublicarviajeDetallesViajeIndexRouteImport.update({
    id: '/publicarviaje/DetallesViaje/',
    path: '/publicarviaje/DetallesViaje/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicarviajeDestinoIndexRoute =
  PublicarviajeDestinoIndexRouteImport.update({
    id: '/publicarviaje/Destino/',
    path: '/publicarviaje/Destino/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuposReservadosValidarCupoBookingIdRoute =
  CuposReservadosValidarCupoBookingIdRouteImport.update({
    id: '/CuposReservados/ValidarCupo/$bookingId',
    path: '/CuposReservados/ValidarCupo/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/Actividades': typeof ActividadesIndexRoute
  '/Chat': typeof ChatIndexRoute
  '/CompletarRegistro': typeof CompletarRegistroIndexRoute
  '/Cupones': typeof CuponesIndexRoute
  '/Cupos': typeof CuposIndexRoute
  '/CuposReservados': typeof CuposReservadosIndexRoute
  '/DateSelected': typeof DateSelectedIndexRoute
  '/Login': typeof LoginIndexRoute
  '/Perfil': typeof PerfilIndexRoute
  '/RecuperarPasword': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo': typeof RegistrarVehiculoIndexRoute
  '/Registro': typeof RegistroIndexRoute
  '/Reservas': typeof ReservasIndexRoute
  '/SafePoints': typeof SafePointsIndexRoute
  '/Wallet': typeof WalletIndexRoute
  '/account': typeof AccountIndexRoute
  '/ayuda': typeof AyudaIndexRoute
  '/change': typeof ChangeIndexRoute
  '/home': typeof HomeIndexRoute
  '/publicarviaje': typeof PublicarviajeIndexRoute
  '/reservar': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
  '/publicarviaje/Destino': typeof PublicarviajeDestinoIndexRoute
  '/publicarviaje/DetallesViaje': typeof PublicarviajeDetallesViajeIndexRoute
  '/publicarviaje/Origen': typeof PublicarviajeOrigenIndexRoute
  '/publicarviaje/Paradas': typeof PublicarviajeParadasIndexRoute
  '/publicarviaje/asientos-precio': typeof PublicarviajeAsientosPrecioIndexRoute
  '/publicarviaje/fecha-hora': typeof PublicarviajeFechaHoraIndexRoute
  '/publicarviaje/punto-recogida': typeof PublicarviajePuntoRecogidaIndexRoute
  '/publicarviaje/puntos-descenso': typeof PublicarviajePuntosDescensoIndexRoute
  '/publicarviaje/resumen-confirmacion': typeof PublicarviajeResumenConfirmacionIndexRoute
  '/publicarviaje/rutas': typeof PublicarviajeRutasIndexRoute
  '/publicarviaje/vehiculo-preferencias': typeof PublicarviajeVehiculoPreferenciasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/Actividades': typeof ActividadesIndexRoute
  '/Chat': typeof ChatIndexRoute
  '/CompletarRegistro': typeof CompletarRegistroIndexRoute
  '/Cupones': typeof CuponesIndexRoute
  '/Cupos': typeof CuposIndexRoute
  '/CuposReservados': typeof CuposReservadosIndexRoute
  '/DateSelected': typeof DateSelectedIndexRoute
  '/Login': typeof LoginIndexRoute
  '/Perfil': typeof PerfilIndexRoute
  '/RecuperarPasword': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo': typeof RegistrarVehiculoIndexRoute
  '/Registro': typeof RegistroIndexRoute
  '/Reservas': typeof ReservasIndexRoute
  '/SafePoints': typeof SafePointsIndexRoute
  '/Wallet': typeof WalletIndexRoute
  '/account': typeof AccountIndexRoute
  '/ayuda': typeof AyudaIndexRoute
  '/change': typeof ChangeIndexRoute
  '/home': typeof HomeIndexRoute
  '/publicarviaje': typeof PublicarviajeIndexRoute
  '/reservar': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
  '/publicarviaje/Destino': typeof PublicarviajeDestinoIndexRoute
  '/publicarviaje/DetallesViaje': typeof PublicarviajeDetallesViajeIndexRoute
  '/publicarviaje/Origen': typeof PublicarviajeOrigenIndexRoute
  '/publicarviaje/Paradas': typeof PublicarviajeParadasIndexRoute
  '/publicarviaje/asientos-precio': typeof PublicarviajeAsientosPrecioIndexRoute
  '/publicarviaje/fecha-hora': typeof PublicarviajeFechaHoraIndexRoute
  '/publicarviaje/punto-recogida': typeof PublicarviajePuntoRecogidaIndexRoute
  '/publicarviaje/puntos-descenso': typeof PublicarviajePuntosDescensoIndexRoute
  '/publicarviaje/resumen-confirmacion': typeof PublicarviajeResumenConfirmacionIndexRoute
  '/publicarviaje/rutas': typeof PublicarviajeRutasIndexRoute
  '/publicarviaje/vehiculo-preferencias': typeof PublicarviajeVehiculoPreferenciasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/Actividades/ActividadesPage': typeof ActividadesActividadesPageRoute
  '/Cupos/ViewBookingDetails': typeof CuposViewBookingDetailsRoute
  '/Cupos/ViewPassengers': typeof CuposViewPassengersRoute
  '/Cupos/ViewTicket': typeof CuposViewTicketRoute
  '/RecuperarPasword/ForgotPassword': typeof RecuperarPaswordForgotPasswordRoute
  '/Actividades/': typeof ActividadesIndexRoute
  '/Chat/': typeof ChatIndexRoute
  '/CompletarRegistro/': typeof CompletarRegistroIndexRoute
  '/Cupones/': typeof CuponesIndexRoute
  '/Cupos/': typeof CuposIndexRoute
  '/CuposReservados/': typeof CuposReservadosIndexRoute
  '/DateSelected/': typeof DateSelectedIndexRoute
  '/Login/': typeof LoginIndexRoute
  '/Perfil/': typeof PerfilIndexRoute
  '/RecuperarPasword/': typeof RecuperarPaswordIndexRoute
  '/RegistrarVehiculo/': typeof RegistrarVehiculoIndexRoute
  '/Registro/': typeof RegistroIndexRoute
  '/Reservas/': typeof ReservasIndexRoute
  '/SafePoints/': typeof SafePointsIndexRoute
  '/Wallet/': typeof WalletIndexRoute
  '/account/': typeof AccountIndexRoute
  '/ayuda/': typeof AyudaIndexRoute
  '/change/': typeof ChangeIndexRoute
  '/home/': typeof HomeIndexRoute
  '/publicarviaje/': typeof PublicarviajeIndexRoute
  '/reservar/': typeof ReservarIndexRoute
  '/CuposReservados/ValidarCupo/$bookingId': typeof CuposReservadosValidarCupoBookingIdRoute
  '/publicarviaje/Destino/': typeof PublicarviajeDestinoIndexRoute
  '/publicarviaje/DetallesViaje/': typeof PublicarviajeDetallesViajeIndexRoute
  '/publicarviaje/Origen/': typeof PublicarviajeOrigenIndexRoute
  '/publicarviaje/Paradas/': typeof PublicarviajeParadasIndexRoute
  '/publicarviaje/asientos-precio/': typeof PublicarviajeAsientosPrecioIndexRoute
  '/publicarviaje/fecha-hora/': typeof PublicarviajeFechaHoraIndexRoute
  '/publicarviaje/punto-recogida/': typeof PublicarviajePuntoRecogidaIndexRoute
  '/publicarviaje/puntos-descenso/': typeof PublicarviajePuntosDescensoIndexRoute
  '/publicarviaje/resumen-confirmacion/': typeof PublicarviajeResumenConfirmacionIndexRoute
  '/publicarviaje/rutas/': typeof PublicarviajeRutasIndexRoute
  '/publicarviaje/vehiculo-preferencias/': typeof PublicarviajeVehiculoPreferenciasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/Actividades'
    | '/Chat'
    | '/CompletarRegistro'
    | '/Cupones'
    | '/Cupos'
    | '/CuposReservados'
    | '/DateSelected'
    | '/Login'
    | '/Perfil'
    | '/RecuperarPasword'
    | '/RegistrarVehiculo'
    | '/Registro'
    | '/Reservas'
    | '/SafePoints'
    | '/Wallet'
    | '/account'
    | '/ayuda'
    | '/change'
    | '/home'
    | '/publicarviaje'
    | '/reservar'
    | '/CuposReservados/ValidarCupo/$bookingId'
    | '/publicarviaje/Destino'
    | '/publicarviaje/DetallesViaje'
    | '/publicarviaje/Origen'
    | '/publicarviaje/Paradas'
    | '/publicarviaje/asientos-precio'
    | '/publicarviaje/fecha-hora'
    | '/publicarviaje/punto-recogida'
    | '/publicarviaje/puntos-descenso'
    | '/publicarviaje/resumen-confirmacion'
    | '/publicarviaje/rutas'
    | '/publicarviaje/vehiculo-preferencias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/Actividades'
    | '/Chat'
    | '/CompletarRegistro'
    | '/Cupones'
    | '/Cupos'
    | '/CuposReservados'
    | '/DateSelected'
    | '/Login'
    | '/Perfil'
    | '/RecuperarPasword'
    | '/RegistrarVehiculo'
    | '/Registro'
    | '/Reservas'
    | '/SafePoints'
    | '/Wallet'
    | '/account'
    | '/ayuda'
    | '/change'
    | '/home'
    | '/publicarviaje'
    | '/reservar'
    | '/CuposReservados/ValidarCupo/$bookingId'
    | '/publicarviaje/Destino'
    | '/publicarviaje/DetallesViaje'
    | '/publicarviaje/Origen'
    | '/publicarviaje/Paradas'
    | '/publicarviaje/asientos-precio'
    | '/publicarviaje/fecha-hora'
    | '/publicarviaje/punto-recogida'
    | '/publicarviaje/puntos-descenso'
    | '/publicarviaje/resumen-confirmacion'
    | '/publicarviaje/rutas'
    | '/publicarviaje/vehiculo-preferencias'
  id:
    | '__root__'
    | '/'
    | '/Actividades/ActividadesPage'
    | '/Cupos/ViewBookingDetails'
    | '/Cupos/ViewPassengers'
    | '/Cupos/ViewTicket'
    | '/RecuperarPasword/ForgotPassword'
    | '/Actividades/'
    | '/Chat/'
    | '/CompletarRegistro/'
    | '/Cupones/'
    | '/Cupos/'
    | '/CuposReservados/'
    | '/DateSelected/'
    | '/Login/'
    | '/Perfil/'
    | '/RecuperarPasword/'
    | '/RegistrarVehiculo/'
    | '/Registro/'
    | '/Reservas/'
    | '/SafePoints/'
    | '/Wallet/'
    | '/account/'
    | '/ayuda/'
    | '/change/'
    | '/home/'
    | '/publicarviaje/'
    | '/reservar/'
    | '/CuposReservados/ValidarCupo/$bookingId'
    | '/publicarviaje/Destino/'
    | '/publicarviaje/DetallesViaje/'
    | '/publicarviaje/Origen/'
    | '/publicarviaje/Paradas/'
    | '/publicarviaje/asientos-precio/'
    | '/publicarviaje/fecha-hora/'
    | '/publicarviaje/punto-recogida/'
    | '/publicarviaje/puntos-descenso/'
    | '/publicarviaje/resumen-confirmacion/'
    | '/publicarviaje/rutas/'
    | '/publicarviaje/vehiculo-preferencias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ActividadesActividadesPageRoute: typeof ActividadesActividadesPageRoute
  CuposViewBookingDetailsRoute: typeof CuposViewBookingDetailsRoute
  CuposViewPassengersRoute: typeof CuposViewPassengersRoute
  CuposViewTicketRoute: typeof CuposViewTicketRoute
  RecuperarPaswordForgotPasswordRoute: typeof RecuperarPaswordForgotPasswordRoute
  ActividadesIndexRoute: typeof ActividadesIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  CompletarRegistroIndexRoute: typeof CompletarRegistroIndexRoute
  CuponesIndexRoute: typeof CuponesIndexRoute
  CuposIndexRoute: typeof CuposIndexRoute
  CuposReservadosIndexRoute: typeof CuposReservadosIndexRoute
  DateSelectedIndexRoute: typeof DateSelectedIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  RecuperarPaswordIndexRoute: typeof RecuperarPaswordIndexRoute
  RegistrarVehiculoIndexRoute: typeof RegistrarVehiculoIndexRoute
  RegistroIndexRoute: typeof RegistroIndexRoute
  ReservasIndexRoute: typeof ReservasIndexRoute
  SafePointsIndexRoute: typeof SafePointsIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AyudaIndexRoute: typeof AyudaIndexRoute
  ChangeIndexRoute: typeof ChangeIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  PublicarviajeIndexRoute: typeof PublicarviajeIndexRoute
  ReservarIndexRoute: typeof ReservarIndexRoute
  CuposReservadosValidarCupoBookingIdRoute: typeof CuposReservadosValidarCupoBookingIdRoute
  PublicarviajeDestinoIndexRoute: typeof PublicarviajeDestinoIndexRoute
  PublicarviajeDetallesViajeIndexRoute: typeof PublicarviajeDetallesViajeIndexRoute
  PublicarviajeOrigenIndexRoute: typeof PublicarviajeOrigenIndexRoute
  PublicarviajeParadasIndexRoute: typeof PublicarviajeParadasIndexRoute
  PublicarviajeAsientosPrecioIndexRoute: typeof PublicarviajeAsientosPrecioIndexRoute
  PublicarviajeFechaHoraIndexRoute: typeof PublicarviajeFechaHoraIndexRoute
  PublicarviajePuntoRecogidaIndexRoute: typeof PublicarviajePuntoRecogidaIndexRoute
  PublicarviajePuntosDescensoIndexRoute: typeof PublicarviajePuntosDescensoIndexRoute
  PublicarviajeResumenConfirmacionIndexRoute: typeof PublicarviajeResumenConfirmacionIndexRoute
  PublicarviajeRutasIndexRoute: typeof PublicarviajeRutasIndexRoute
  PublicarviajeVehiculoPreferenciasIndexRoute: typeof PublicarviajeVehiculoPreferenciasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar/': {
      id: '/reservar/'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/': {
      id: '/publicarviaje/'
      path: '/publicarviaje'
      fullPath: '/publicarviaje'
      preLoaderRoute: typeof PublicarviajeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change/': {
      id: '/change/'
      path: '/change'
      fullPath: '/change'
      preLoaderRoute: typeof ChangeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/': {
      id: '/ayuda/'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Wallet/': {
      id: '/Wallet/'
      path: '/Wallet'
      fullPath: '/Wallet'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SafePoints/': {
      id: '/SafePoints/'
      path: '/SafePoints'
      fullPath: '/SafePoints'
      preLoaderRoute: typeof SafePointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reservas/': {
      id: '/Reservas/'
      path: '/Reservas'
      fullPath: '/Reservas'
      preLoaderRoute: typeof ReservasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Registro/': {
      id: '/Registro/'
      path: '/Registro'
      fullPath: '/Registro'
      preLoaderRoute: typeof RegistroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegistrarVehiculo/': {
      id: '/RegistrarVehiculo/'
      path: '/RegistrarVehiculo'
      fullPath: '/RegistrarVehiculo'
      preLoaderRoute: typeof RegistrarVehiculoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RecuperarPasword/': {
      id: '/RecuperarPasword/'
      path: '/RecuperarPasword'
      fullPath: '/RecuperarPasword'
      preLoaderRoute: typeof RecuperarPaswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Perfil/': {
      id: '/Perfil/'
      path: '/Perfil'
      fullPath: '/Perfil'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login/': {
      id: '/Login/'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DateSelected/': {
      id: '/DateSelected/'
      path: '/DateSelected'
      fullPath: '/DateSelected'
      preLoaderRoute: typeof DateSelectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CuposReservados/': {
      id: '/CuposReservados/'
      path: '/CuposReservados'
      fullPath: '/CuposReservados'
      preLoaderRoute: typeof CuposReservadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupos/': {
      id: '/Cupos/'
      path: '/Cupos'
      fullPath: '/Cupos'
      preLoaderRoute: typeof CuposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupones/': {
      id: '/Cupones/'
      path: '/Cupones'
      fullPath: '/Cupones'
      preLoaderRoute: typeof CuponesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CompletarRegistro/': {
      id: '/CompletarRegistro/'
      path: '/CompletarRegistro'
      fullPath: '/CompletarRegistro'
      preLoaderRoute: typeof CompletarRegistroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Chat/': {
      id: '/Chat/'
      path: '/Chat'
      fullPath: '/Chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Actividades/': {
      id: '/Actividades/'
      path: '/Actividades'
      fullPath: '/Actividades'
      preLoaderRoute: typeof ActividadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RecuperarPasword/ForgotPassword': {
      id: '/RecuperarPasword/ForgotPassword'
      path: '/RecuperarPasword/ForgotPassword'
      fullPath: '/RecuperarPasword/ForgotPassword'
      preLoaderRoute: typeof RecuperarPaswordForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupos/ViewTicket': {
      id: '/Cupos/ViewTicket'
      path: '/Cupos/ViewTicket'
      fullPath: '/Cupos/ViewTicket'
      preLoaderRoute: typeof CuposViewTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupos/ViewPassengers': {
      id: '/Cupos/ViewPassengers'
      path: '/Cupos/ViewPassengers'
      fullPath: '/Cupos/ViewPassengers'
      preLoaderRoute: typeof CuposViewPassengersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cupos/ViewBookingDetails': {
      id: '/Cupos/ViewBookingDetails'
      path: '/Cupos/ViewBookingDetails'
      fullPath: '/Cupos/ViewBookingDetails'
      preLoaderRoute: typeof CuposViewBookingDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Actividades/ActividadesPage': {
      id: '/Actividades/ActividadesPage'
      path: '/Actividades/ActividadesPage'
      fullPath: '/Actividades/ActividadesPage'
      preLoaderRoute: typeof ActividadesActividadesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/vehiculo-preferencias/': {
      id: '/publicarviaje/vehiculo-preferencias/'
      path: '/publicarviaje/vehiculo-preferencias'
      fullPath: '/publicarviaje/vehiculo-preferencias'
      preLoaderRoute: typeof PublicarviajeVehiculoPreferenciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/rutas/': {
      id: '/publicarviaje/rutas/'
      path: '/publicarviaje/rutas'
      fullPath: '/publicarviaje/rutas'
      preLoaderRoute: typeof PublicarviajeRutasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/resumen-confirmacion/': {
      id: '/publicarviaje/resumen-confirmacion/'
      path: '/publicarviaje/resumen-confirmacion'
      fullPath: '/publicarviaje/resumen-confirmacion'
      preLoaderRoute: typeof PublicarviajeResumenConfirmacionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/puntos-descenso/': {
      id: '/publicarviaje/puntos-descenso/'
      path: '/publicarviaje/puntos-descenso'
      fullPath: '/publicarviaje/puntos-descenso'
      preLoaderRoute: typeof PublicarviajePuntosDescensoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/punto-recogida/': {
      id: '/publicarviaje/punto-recogida/'
      path: '/publicarviaje/punto-recogida'
      fullPath: '/publicarviaje/punto-recogida'
      preLoaderRoute: typeof PublicarviajePuntoRecogidaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/fecha-hora/': {
      id: '/publicarviaje/fecha-hora/'
      path: '/publicarviaje/fecha-hora'
      fullPath: '/publicarviaje/fecha-hora'
      preLoaderRoute: typeof PublicarviajeFechaHoraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/asientos-precio/': {
      id: '/publicarviaje/asientos-precio/'
      path: '/publicarviaje/asientos-precio'
      fullPath: '/publicarviaje/asientos-precio'
      preLoaderRoute: typeof PublicarviajeAsientosPrecioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/Paradas/': {
      id: '/publicarviaje/Paradas/'
      path: '/publicarviaje/Paradas'
      fullPath: '/publicarviaje/Paradas'
      preLoaderRoute: typeof PublicarviajeParadasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/Origen/': {
      id: '/publicarviaje/Origen/'
      path: '/publicarviaje/Origen'
      fullPath: '/publicarviaje/Origen'
      preLoaderRoute: typeof PublicarviajeOrigenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/DetallesViaje/': {
      id: '/publicarviaje/DetallesViaje/'
      path: '/publicarviaje/DetallesViaje'
      fullPath: '/publicarviaje/DetallesViaje'
      preLoaderRoute: typeof PublicarviajeDetallesViajeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicarviaje/Destino/': {
      id: '/publicarviaje/Destino/'
      path: '/publicarviaje/Destino'
      fullPath: '/publicarviaje/Destino'
      preLoaderRoute: typeof PublicarviajeDestinoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CuposReservados/ValidarCupo/$bookingId': {
      id: '/CuposReservados/ValidarCupo/$bookingId'
      path: '/CuposReservados/ValidarCupo/$bookingId'
      fullPath: '/CuposReservados/ValidarCupo/$bookingId'
      preLoaderRoute: typeof CuposReservadosValidarCupoBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ActividadesActividadesPageRoute: ActividadesActividadesPageRoute,
  CuposViewBookingDetailsRoute: CuposViewBookingDetailsRoute,
  CuposViewPassengersRoute: CuposViewPassengersRoute,
  CuposViewTicketRoute: CuposViewTicketRoute,
  RecuperarPaswordForgotPasswordRoute: RecuperarPaswordForgotPasswordRoute,
  ActividadesIndexRoute: ActividadesIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  CompletarRegistroIndexRoute: CompletarRegistroIndexRoute,
  CuponesIndexRoute: CuponesIndexRoute,
  CuposIndexRoute: CuposIndexRoute,
  CuposReservadosIndexRoute: CuposReservadosIndexRoute,
  DateSelectedIndexRoute: DateSelectedIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  RecuperarPaswordIndexRoute: RecuperarPaswordIndexRoute,
  RegistrarVehiculoIndexRoute: RegistrarVehiculoIndexRoute,
  RegistroIndexRoute: RegistroIndexRoute,
  ReservasIndexRoute: ReservasIndexRoute,
  SafePointsIndexRoute: SafePointsIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  AyudaIndexRoute: AyudaIndexRoute,
  ChangeIndexRoute: ChangeIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  PublicarviajeIndexRoute: PublicarviajeIndexRoute,
  ReservarIndexRoute: ReservarIndexRoute,
  CuposReservadosValidarCupoBookingIdRoute:
    CuposReservadosValidarCupoBookingIdRoute,
  PublicarviajeDestinoIndexRoute: PublicarviajeDestinoIndexRoute,
  PublicarviajeDetallesViajeIndexRoute: PublicarviajeDetallesViajeIndexRoute,
  PublicarviajeOrigenIndexRoute: PublicarviajeOrigenIndexRoute,
  PublicarviajeParadasIndexRoute: PublicarviajeParadasIndexRoute,
  PublicarviajeAsientosPrecioIndexRoute: PublicarviajeAsientosPrecioIndexRoute,
  PublicarviajeFechaHoraIndexRoute: PublicarviajeFechaHoraIndexRoute,
  PublicarviajePuntoRecogidaIndexRoute: PublicarviajePuntoRecogidaIndexRoute,
  PublicarviajePuntosDescensoIndexRoute: PublicarviajePuntosDescensoIndexRoute,
  PublicarviajeResumenConfirmacionIndexRoute:
    PublicarviajeResumenConfirmacionIndexRoute,
  PublicarviajeRutasIndexRoute: PublicarviajeRutasIndexRoute,
  PublicarviajeVehiculoPreferenciasIndexRoute:
    PublicarviajeVehiculoPreferenciasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
